services:
  - type: web
    name: player_charts
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn player_charts.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dplayer_charts
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4