# Generated by Django 4.0.5 on 2022-09-02 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_player_matches_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Stats_by_Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('competition', models.CharField(max_length=100)),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('defeats', models.IntegerField()),
                ('team_goals', models.IntegerField()),
                ('season', models.CharField(max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.player')),
            ],
        ),
    ]
